<!DOCTYPE html>
<html lang="en">
  <head>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]--> 
    <meta charset="utf-8">
    <title>Jade4PHP - Amazium Page</title>
    <meta name="description" content="Jade4PHP is a an extension for Jade.js allowing you to create beautiful jade templates for PHP">
    <meta name="author" content="Brian Etherington">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,300,400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/base.css">
    <link rel="stylesheet" href="css/amazium.css">
    <link rel="stylesheet" href="css/form.css">
    <link rel="stylesheet" href="css/layout.css">
    <link rel="shortcut icon" href="img/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon.png">
  </head>
  <body>
    <header class="row">
      <div class="grid_6"><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-screen">
            <image src="img/logo.png"></image></a></span><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-tablet">
            <image src="img/logo.png"></image></a></span><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-mobile float-left">
            <image src="img/logo.png" width="200px"></image></a></span><span><a id="navigation-btn" href="#" class="show-mobile"> <span class="fa fa-bars fa-2x"></span></a></span></div>
      <div class="grid_6 txt-right">
        <h3 class="download"><a href="https://github.com/BookArt/jade4php-example/archive/master.zip">download&nbsp;<span class="fa fa-download"></span></a></h3>
        <div class="social">
          <!-- AddToAny BEGIN-->
          <div class="a2a_kit a2a_kit_size_32 a2a_default_style"><a class="a2a_button_facebook"></a><a class="a2a_button_twitter"></a><a class="a2a_button_google_plus"></a><a class="a2a_button_tumblr"></a>
          </div>
          <script type="text/javascript">
            var a2a_config = a2a_config || {};
            a2a_config.linkname = "jade4php";
            a2a_config.linkurl = "http://www.jade4php.com";
          </script>
          <script type="text/javascript" src="//static.addtoany.com/menu/page.js"></script>
          <!-- AddToAny END-->
        </div>
      </div>
      <hr>
    </header>
    <section class="row"><br>
      <h2 class="indent">Getting started with jade4php</h2><br>
    </section>
    <section class="row">
      <article id="navigation" class="grid_3">
        <nav class="navpanel">
          <ol>    
            <li><a href="index.php"><span class="number"></span><span class="label">Introduction</span></a><span class="arrow"></span></li>
            <li><a href="setup.php"><span class="number"></span><span class="label">Setup</span></a><span class="arrow"></span></li>
            <li><a href="project.php"><span class="number"></span><span class="label">Project Folders</span></a><span class="arrow"></span></li>
            <li><a href="paras.php"><span class="number"></span><span class="label">Paragraph Text</span></a><span class="arrow"></span></li>
            <li><a href="tables.php"><span class="number"></span><span class="label">Tables</span></a><span class="arrow"></span></li>
            <li><a href="menu.php"><span class="number"></span><span class="label">Menus</span></a><span class="arrow"></span></li>
            <li><a href="conditional.php"><span class="number"></span><span class="label">Conditional PHP</span></a><span class="arrow"></span></li>
            <li class="selected"><a href="#"><span class="number"></span><span class="label">Amazium CSS</span></a><span class="arrow"></span></li>
            <li><a href="forms.php"><span class="number"></span><span class="label">Amazium Forms</span></a><span class="arrow"></span></li>
          </ol>
        </nav>
      </article>
      <article class="grid_9">
        <section class="row">
          <article class="grid_8">    
            <h2>The Amazium Responsive CSS Framework</h2>
            <p>
              I really like Amazium. It is beautifully simple and the perfect partner for your Jade Templates. 
               On this page you will find some examples 
              of what you can with it, If you want to know more head over to <a href="http://www.amazium.co.uk" target="_blank">www.amazium.co.uk</a> for a complete description and examples.
            </p>
          </article>
        </section>
        <section class="row grid-highlight">
          <article class="grid_1">1</article>
          <article class="grid_1">1</article>
          <article class="grid_1">1</article>
          <article class="grid_1">1</article>
          <article class="grid_1">1</article>
          <article class="grid_1">1</article>
          <article class="grid_1">1</article>
          <article class="grid_1">1</article>
        </section>
        <section class="row grid-highlight">
          <article class="grid_2">2</article>
          <article class="grid_2">2</article>
          <article class="grid_2">2</article>
          <article class="grid_2">2</article>
        </section>
        <section class="row grid-highlight">
          <article class="grid_4">4</article>
          <article class="grid_4">4</article>
        </section>
        <section class="row grid-highlight">
          <article class="grid_6">6</article>
          <article class="grid_2">2</article>
        </section>
        <section class="row grid-highlight">
          <article class="grid_8">8</article>
        </section>
        <section class="row">
          <article class="grid_8">
            <hr>
            <h3>Buttons</h3>
            <p><a href="#" class="btn">Normal Button</a><a href="#" class="btn red">Red Button</a><a href="#" class="btn blue">Blue Button</a><a href="#" class="btn green">Green Button</a><a href="#" class="btn white">White Button</a></p>
            <p><a href="#" class="btn small">Small Button</a><a href="#" class="btn red small">Small Red Button</a><a href="#" class="btn blue small">Small Blue Button</a><a href="#" class="btn green small">Small Green Button</a><a href="#" class="btn white small">Small White Button</a></p>
            <hr>
            <h3>Tables</h3>
            <table summary="This is an example of a table">
              <thead>
                <tr>
                  <th scope="col">#ID:</th>
                  <th scope="col">First Name:</th>
                  <th scope="col">Last Name:</th>
                  <th scope="col">Location:</th>
                </tr>
              </thead>
              <tbody><?php foreach($table as $row): ?>
                <tr>
                  <td>#<?php echo htmlspecialchars($row['id'], ENT_QUOTES, 'UTF-8'); ?></td>
                  <td><?php echo htmlspecialchars($row['first_name'], ENT_QUOTES, 'UTF-8'); ?></td>
                  <td><?php echo htmlspecialchars($row['last_name'], ENT_QUOTES, 'UTF-8'); ?></td>
                  <td><?php echo htmlspecialchars($row['location'], ENT_QUOTES, 'UTF-8'); ?></td>
                </tr><?php endforeach; ?>
              </tbody>
            </table>
            <hr>
          </article>
        </section>
        <section class="row">
          <article class="grid_4">
            <h3>100% Video</h3>
            <div class="media">
              <iframe src="http://player.vimeo.com/video/21465475?title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff&amp;autoplay=0" frameborder="0"></iframe>
            </div>
          </article>
          <article class="grid_4">
            <h3>100% Image</h3><img src="img/blank.jpg" border="0" alt="blank image" class="img-max">
          </article>
        </section>
      </article>
    </section>
    <footer class="row txt-center">
      <nav class="navfoot">  
        <ul>    
          <li><a href="index.php">Introduction</a></li>
          <li><a href="setup.php">Setup</a></li>
          <li><a href="project.php">Project Folders</a></li>
          <li><a href="paras.php">Paragraph Text</a></li>
          <li><a href="tables.php">Tables</a></li>
          <li><a href="menu.php">Menus</a></li>
          <li><a href="conditional.php">Conditional PHP</a></li>
          <li><a href="forms.php">Amazium Forms</a></li>
        </ul>
      </nav>Copyright 2014 <a href="http://www.jade4php.com">www.jade4php.com</a>. All rights reserved.<br>
    </footer>
    <script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="js/amazium.js"></script>
    <script type="text/javascript">
      function toggleNavigationClass() {
        if ( document.getElementById('navigation').className.match(/(?:^|\s)showme(?!\S)/) ) {
          document.getElementById('navigation').className =
              document.getElementById('navigation').className.replace( /(?:^|\s)showme(?!\S)/g , '' );
        } else {
          document.getElementById("navigation").className += " showme";
        }
      }
      window.onload = function() {
        var navigationBtnId = document.getElementById('navigation-btn');
        if (navigationBtnId != null) {
          navigationBtnId.addEventListener( 'click' , toggleNavigationClass );
        }
      }
    </script>
  </body>
</html>