<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Jade4PHP example - Amazium Forms</title>
    <meta name="description" content="">
    <meta name="author" content=""><!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,300,400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/base.css">
    <link rel="stylesheet" href="css/amazium.css">
    <link rel="stylesheet" href="css/form.css">
    <link rel="stylesheet" href="css/layout.css">
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon.png">
  </head>
  <body>
    <header class="row">
      <div class="grid_6"><a href="https://github.com/BookArt/jade4php" target="_blank">
          <image src="img/logo.png"></image></a></div>
      <div class="grid_6 txt-right">
        <h3> <a href="https://github.com/BookArt/jade4php-example/archive/master.zip">download&nbsp;<span class="fa fa-download"></span></a></h3><br>
        <div class="social">&nbsp
        </div>
      </div>
      <hr>
    </header>
    <section class="row"><br>
      <h2 class="page-title">Getting started with jade4php</h2><br>
    </section>
    <section class="row">
      <article class="grid_3">
        <nav class="navpanel">
          <ol>    
            <li><a href="index.php"><span class="number"></span><span class="label">introduction</span></a><span class="arrow"></span></li>
            <li><a href="setup.php"><span class="number"></span><span class="label">Setup</span></a><span class="arrow"></span></li>
            <li><a href="project.php"><span class="number"></span><span class="label">Project Folders</span></a><span class="arrow"></span></li>
            <li><a href="paras.php"><span class="number"></span><span class="label">Paragraph Text</span></a><span class="arrow"></span></li>
            <li><a href="tables.php"><span class="number"></span><span class="label">Tables</span></a><span class="arrow"></span></li>
            <li><a href="menu.php"><span class="number"></span><span class="label">Menus</span></a><span class="arrow"></span></li>
            <li><a href="conditional.php"><span class="number"></span><span class="label">Conditional PHP</span></a><span class="arrow"></span></li>
            <li><a href="amazium.php"><span class="number"></span><span class="label">Amazium CSS</span></a><span class="arrow"></span></li>
            <li class="selected"><a href="#"><span class="number"></span><span class="label">Amazium Forms</span></a><span class="arrow"></span></li>
          </ol>
        </nav>
      </article>
      <article class="grid_9">
        <h2>Amazium Forms</h2>
        <p>Thanks to the awesome <a href="https://github.com/shahrukhomar" target="_blank">Shahrukh Omar </a>who has made it possible to show the label of an input when the user starts 
          typing in a field so know what each field is. All you will need to do is add 
          css class nysmnyd-labels 
          to your form and make sure you have the Amazium.js file included and you too 
          will have fancy show/hide lables on your inputs.
        </p>
        <form name="" method="" action="" class="nysmnyd-labels">
          <section class="row">
            <article class="grid_4">
              <fieldset>
                <label for="text">Text</label>
                <input id="text" type="text" name="text" placeholder="Text" tabindex="1">
              </fieldset>
              <fieldset>
                <label for="password">Password</label>
                <input id="password" type="password" name="password" placeholder="Password" tabindex="2">
              </fieldset>
              <fieldset>
                <label for="url">URL</label>
                <input id="url" type="url" name="url" placeholder="Url" tabindex="3">
              </fieldset>
              <fieldset>
                <label for="tel">Tel</label>
                <input id="tel" type="tel" name="tel" placeholder="Tel" tabindex="4">
              </fieldset>
            </article>
            <article class="grid_4">
              <fieldset>
                <label for="email">Email</label>
                <input id="email" type="email" name="email" placeholder="Email" tabindex="5">
              </fieldset>
              <fieldset>
                <label for="options">Options</label><span class="select">
                  <select id="dropdown" name="dropdown" tabindex="6">
                    <option selected="">Option 1</option>
                    <option>Option 2</option>
                    <option>Option 3</option>
                  </select></span>
              </fieldset>
              <fieldset>
                <label for="message">Message</label>
                <textarea id="message" name="message" placeholder="Message..." tabindex="7"></textarea>
              </fieldset>
            </article>
          </section>
          <section class="row">
            <article class="grid_4">&nbsp;</article>
            <article class="grid_2">         
              <input id="submitbtn" type="reset" name="reset" tabindex="8" value="Reset">
            </article>
            <article class="grid_2">
              <input id="submitbtn" type="submit" name="submit" tabindex="9" value="Submit">
            </article>
          </section>
        </form>
        <h3>paras.jade</h3>
        <pre><code>form.nysmnyd-labels(name='', method='', action='')
  - tab_index = 1
  section.row
    article.grid_4
      fieldset
        label(for='text') Text
        input#text(type='text', name='text', placeholder='Text', tabindex='&num;{tab_index++}')
      fieldset
        label(for='password') Password
        input#password(type='password', name='password', placeholder='Password', tabindex='&num;{tab_index++}')
      fieldset
        label(for='url') URL
        input#url(type='url', name='url', placeholder='Url', tabindex='&num;{tab_index++}')
      fieldset
        label(for='tel') Tel
        input#tel(type='tel', name='tel', placeholder='Tel', tabindex='&num;{tab_index++}')
    article.grid_4
      fieldset
        label(for='email') Email
        input#email(type='email', name='email', placeholder='Email', tabindex='&num;{tab_index++}')
      fieldset
        label(for='options') Options
        span.select
          select#dropdown(name='dropdown', tabindex='&num;{tab_index++}')
            option(selected='') Option 1
            option Option 2
            option Option 3
      fieldset
        label(for='message') Message
        textarea#message(name='message', placeholder='Message...', tabindex='&num;{tab_index++}')  
  section.row
    article.grid_4 &amp;nbsp;
    article.grid_2          
      input#submitbtn(type='reset', name='reset', tabindex='&num;{tab_index++}', value='Reset') 
    article.grid_2
      input#submitbtn(type='submit', name='submit', tabindex='&num;{tab_index++}', value='Submit')    </code></pre>
        <h3>paras.php</h3>
        <pre><code>&lt;?php
include "lib/Template.class.php";
$template = new Template();
$template-&gt;display('templates/forms.phtml');</code></pre>
      </article>
    </section>
    <footer class="row txt-center">
      <nav class="navfoot">  
        <ul>    
          <li><a href="index.php">introduction</a></li>
          <li><a href="setup.php">Setup</a></li>
          <li><a href="project.php">Project Folders</a></li>
          <li><a href="paras.php">Paragraph Text</a></li>
          <li><a href="tables.php">Tables</a></li>
          <li><a href="menu.php">Menus</a></li>
          <li><a href="conditional.php">Conditional PHP</a></li>
          <li><a href="amazium.php">Amazium CSS</a></li>
        </ul>
      </nav>Copyright 2014 <a href="http://www.jade4php.com">www.jade4php.com</a>. All rights reserved.<br>
    </footer>
    <script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="js/amazium.js"></script>
  </body>
</html>