<!DOCTYPE html>
<html lang="en">
  <head>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]--> 
    <meta charset="utf-8">
    <title>Jade4PHP - Introduction</title>
    <meta name="description" content="Jade4PHP is a an extension for Jade.js allowing you to create beautiful jade templates for PHP">
    <meta name="author" content="Brian Etherington">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,300,400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/base.css">
    <link rel="stylesheet" href="css/amazium.css">
    <link rel="stylesheet" href="css/form.css">
    <link rel="stylesheet" href="css/layout.css">
    <link rel="shortcut icon" href="img/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon.png">
  </head>
  <body>
    <header class="row">
      <div class="grid_6"><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-screen">
            <image src="img/logo.png"></image></a></span><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-tablet">
            <image src="img/logo.png"></image></a></span><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-mobile float-left">
            <image src="img/logo.png" width="200px"></image></a></span><span><a id="navigation-btn" href="#" class="show-mobile"> <span class="fa fa-bars fa-2x"></span></a></span></div>
      <div class="grid_6 txt-right">
        <h3 class="download"><a href="https://github.com/BookArt/jade4php-example/archive/master.zip">download&nbsp;<span class="fa fa-download"></span></a></h3>
        <div class="social">
          <!-- AddToAny BEGIN-->
          <div class="a2a_kit a2a_kit_size_32 a2a_default_style"><a class="a2a_button_facebook"></a><a class="a2a_button_twitter"></a><a class="a2a_button_google_plus"></a><a class="a2a_button_tumblr"></a>
          </div>
          <script type="text/javascript">
            var a2a_config = a2a_config || {};
            a2a_config.linkname = "jade4php";
            a2a_config.linkurl = "http://www.jade4php.com";
          </script>
          <script type="text/javascript" src="//static.addtoany.com/menu/page.js"></script>
          <!-- AddToAny END-->
        </div>
      </div>
      <hr>
    </header>
    <section class="row"><br>
      <h2 class="indent">Getting started with jade4php</h2><br>
    </section>
    <section class="row">
      <article id="navigation" class="grid_3">
        <nav class="navpanel">
          <ol>    
            <li class="selected"><a href="#"><span class="number"></span><span class="label">Introduction</span></a><span class="arrow"></span></li>
            <li><a href="setup.php"><span class="number"></span><span class="label">Setup</span></a><span class="arrow"></span></li>
            <li><a href="project.php"><span class="number"></span><span class="label">Project Folders</span></a><span class="arrow"></span></li>
            <li><a href="paras.php"><span class="number"></span><span class="label">Paragraph Text</span></a><span class="arrow"></span></li>
            <li><a href="tables.php"><span class="number"></span><span class="label">Tables</span></a><span class="arrow"></span></li>
            <li><a href="menu.php"><span class="number"></span><span class="label">Menus</span></a><span class="arrow"></span></li>
            <li><a href="conditional.php"><span class="number"></span><span class="label">Conditional PHP</span></a><span class="arrow"></span></li>
            <li><a href="amazium.php"><span class="number"></span><span class="label">Amazium CSS</span></a><span class="arrow"></span></li>
            <li><a href="forms.php"><span class="number"></span><span class="label">Amazium Forms</span></a><span class="arrow"></span></li>
          </ol>
        </nav>
      </article>
      <article class="grid_9">
        <figure>
          <blockquote>
            <p>
               
              O how much more doth beauty beauteous seem, <br>By that sweet ornament which truth doth give!<br>The rose looks fair, but fairer we it deem <br>For that sweet odour which doth in it live.
            </p>
          </blockquote>
          <figcaption>William Shakespeare</figcaption>
        </figure><br><br>
        <p class="intro">Are you seduced by the elegance and beauty of <a href="http://jade-lang.com" target="_blank">Jade templates</a> and wish that you could share that same zen 
          experience in your own PHP code projects?  Well now you can with the help of jade4php.  <a href="https://github.com/BookArt/jade4php-example/archive/master.zip">Download the example project</a> from this website and walk through the tutorial to see how you too can wander lonely as a 
          cloud, that floats on high o'er vales and hill...
        </p>
        <h2>Jade is HTML without tags</h2>
        <pre><code>doctype html
html(lang="en")
  head
    meta(charset="utf-8")
    title Jade4PHP - Introduction
    meta(name="description" content="")
    meta(name="author" content="")
    //- Mobile Specific Metas
    meta(name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1")  
  body
    div
      h1 Jade is Wonderful....
    div
      p.
        Nullam a dolor id arcu semper finibus ut pulvinar orci. Proin 
        sodales nisi et dictum pulvinar. Duis orci velit, suscipit et 
        porttitor gravida, molestie ac purus. Cum sociis natoque penatibus 
        et magnis dis parturient montes, nascetur ridiculus mus. Cras felis 
        neque, gravida a blandit ac, rutrum ut sapien. Vivamus tincidunt 
        volutpat libero eget tempor. Nam dolor mauris, mollis in euismod 
        vitae, viverra ac libero
    div
      p Copyright 2014 www.jade4php.com. All rights reserved.
    //- Scripts
    script(type="text/javascript" src="js/jquery-1.8.0.min.js")</code></pre>
        <h2>Produces...</h2>
        <pre>
          <p>&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
    &lt;head&gt;
        &lt;meta charset="utf-8"&gt;
        &lt;title&gt;&lt;/title&gt;
        &lt;meta name="description" content=""&gt;
        &lt;meta name="author" content=""&gt;
        &lt;meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;div&gt;
            &lt;h1&gt;Jade is Wonderful....&lt;/h1&gt;
        &lt;/div&gt;
        &lt;div&gt;
            &lt;p&gt;
                Nullam a dolor id arcu semper finibus ut pulvinar orci. Proin 
                sodales nisi et dictum pulvinar. Duis orci velit, suscipit et 
                porttitor gravida, molestie ac purus. Cum sociis natoque penatibus 
                et magnis dis parturient montes, nascetur ridiculus mus. Cras felis 
                neque, gravida a blandit ac, rutrum ut sapien. Vivamus tincidunt 
                volutpat libero eget tempor. Nam dolor mauris, mollis in euismod 
                vitae, viverra ac libero
            &lt;/p&gt;
        &lt;/div&gt;
        &lt;div&gt;
            &lt;p&gt;Copyright 2014 www.jade4php.com. All rights reserved.&lt;/p&gt;
        &lt;/div&gt;
        &lt;script type="text/javascript" src="js/jquery-1.8.0.min.js"&gt;&lt;/script&gt;
    &lt;/body&gt;
&lt;/html&gt;
          </p></pre><br>
        <p>Check out the full Jade syntax at <a href="http://jade-lang.com/reference" target="_blank">http://jade-lang.com/reference</a> and see what it can do.</p>
        <h2> 
          <image src="img/logo_small.png"></image> ...
        </h2>
        <ul class="indent">
          <li>Is a Jade extension to create beautiful php html templates.</li>
          <li>Fully supports all standard jade syntax including compile time variables and conditional code.</li>
          <li>Adds support for single line of text in filters where a text block does not follow the filter.</li>
        </ul>
        <pre><code>e.g. :php if ($test == 1):

as well as blocks of text:

    :php
      $var1 = 'foo';
      $var1 = 'bar';</code></pre>
        <p>
          Jade4php adds a simple php function to return a formatted php string allowing it to be stored in a run 
          time javascript variable.
        </p>
        <pre><code>e.g. - test = php('$foo');

will asign to variable test:

&lt;?php echo htmlspecialchars($foo, ENT_QUOTES, 'UTF-8'); ?&gt;   </code></pre>
        <p>
          Note: the formatted strings must be displayed Unescaped because the formatting includes &lt;php and ?&gt; characters.  
          Don't worry, the expression argument to the php function call is fully escaped at runtime with the php htmlspecialchars function as in the above example. 
          
        </p>
        <p>However, note that it is possible to set a no_escape flag (but you probably don't want to do this):</p>
        <pre><code>- test = php('$foo', true);

will asign to variable test:

&lt;?php echo $foo; ?&gt;</code></pre>
      </article>
    </section>
    <footer class="row txt-center">
      <nav class="navfoot">  
        <ul>    
          <li><a href="setup.php">Setup</a></li>
          <li><a href="project.php">Project Folders</a></li>
          <li><a href="paras.php">Paragraph Text</a></li>
          <li><a href="tables.php">Tables</a></li>
          <li><a href="menu.php">Menus</a></li>
          <li><a href="conditional.php">Conditional PHP</a></li>
          <li><a href="amazium.php">Amazium CSS</a></li>
          <li><a href="forms.php">Amazium Forms</a></li>
        </ul>
      </nav>Copyright 2014 <a href="http://www.jade4php.com">www.jade4php.com</a>. All rights reserved.<br>
    </footer>
    <script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="js/amazium.js"></script>
    <script type="text/javascript">
      function toggleNavigationClass() {
        if ( document.getElementById('navigation').className.match(/(?:^|\s)showme(?!\S)/) ) {
          document.getElementById('navigation').className =
              document.getElementById('navigation').className.replace( /(?:^|\s)showme(?!\S)/g , '' );
        } else {
          document.getElementById("navigation").className += " showme";
        }
      }
      window.onload = function() {
        var navigationBtnId = document.getElementById('navigation-btn');
        if (navigationBtnId != null) {
          navigationBtnId.addEventListener( 'click' , toggleNavigationClass );
        }
      }
    </script>
  </body>
</html>