<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Jade4PHP example - Introduction</title>
    <meta name="description" content="">
    <meta name="author" content=""><!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,300,400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/base.css">
    <link rel="stylesheet" href="css/amazium.css">
    <link rel="stylesheet" href="css/form.css">
    <link rel="stylesheet" href="css/layout.css">
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon.png">
  </head>
  <body>
    <header class="row">
      <div class="grid_6">
        <image src="img/logo.png"></image>
      </div>
      <div class="grid_6 txt-right">
        <h3> <a href="https://github.com/BookArt/jade4php-example/archive/master.zip">download&nbsp;<span class="fa fa-download"></span></a></h3><br>
        <div class="social">&nbsp
        </div>
      </div>
      <hr>
    </header>
    <section class="row"><br>
      <h2 class="page-title">Getting started with jade4php</h2><br>
    </section>
    <section class="row">
      <article class="grid_3">
        <nav class="navpanel">
          <ol>    
            <li class="selected"><a href="#"><span class="number"></span><span class="label">introduction</span></a><span class="arrow"></span></li>
            <li><a href="setup.php"><span class="number"></span><span class="label">Setup</span></a><span class="arrow"></span></li>
            <li><a href="project.php"><span class="number"></span><span class="label">Project Folders</span></a><span class="arrow"></span></li>
            <li><a href="paras.php"><span class="number"></span><span class="label">Paragraph Text</span></a><span class="arrow"></span></li>
            <li><a href="tables.php"><span class="number"></span><span class="label">Tables</span></a><span class="arrow"></span></li>
            <li><a href="menu.php"><span class="number"></span><span class="label">Menus</span></a><span class="arrow"></span></li>
            <li><a href="conditional.php"><span class="number"></span><span class="label">Conditional PHP</span></a><span class="arrow"></span></li>
            <li><a href="amazium.php"><span class="number"></span><span class="label">Amazium CSS</span></a><span class="arrow"></span></li>
            <li><a href="forms.php"><span class="number"></span><span class="label">Amazium Forms</span></a><span class="arrow"></span></li>
          </ol>
        </nav>
      </article>
      <article class="grid_9">
        <figure>
          <blockquote>
            <p>
               
              O how much more doth beauty beauteous seem, <br>By that sweet ornament which truth doth give!<br>The rose looks fair, but fairer we it deem <br>For that sweet odour which doth in it live.
            </p>
          </blockquote>
          <figcaption>William Shakespeare</figcaption>
        </figure><br><br>
        <p>
          Are you seduced by the elegance and beauty of jade templates and wish that you could share that same zen 
          experience in your PHP code projects?  Well now you can with the help of jade4php.  <a href="https://github.com/BookArt/jade4php-example/archive/master.zip">Download the example project</a> from this website and walk through the tutorial to see how you too can wander lonely as a 
          cloud, that floats on high o'er vales and hill...
        </p>
        <h2> 
          <image src="img/logo_small.png"></image> ...
        </h2>
        <ul class="indent">
          <li>Is a Jade extension to create beautiful php html templates.</li>
          <li>Fully supports all standard jade syntax including compile time variables and conditional code.</li>
          <li>Adds support for single line of text in filters where a text block does not follow the filter.</li>
        </ul>
        <pre><code>e.g. :php if ($test == 1):

as well as blocks of text:

    :php
      $var1 = 'foo';
      $var1 = 'bar';</code></pre>
        <p>
          Jade4php adds a simple php function to return a formatted php string allowing it to be stored in a run 
          time javascript variable.
        </p>
        <pre><code>e.g. - test = php('$foo');

will asign to variable test:

&lt;?php echo htmlspecialchars($foo, ENT_QUOTES, 'UTF-8'); ?&gt;   </code></pre>
        <p>
          Note: the formatted strings must be displayed Unescaped because the formatting includes &lt;php and ?&gt; characters.  
          Don't worry, the expression argument to the php function call is fully escaped at runtime with the php htmlspecialchars function as in the above example. 
          
        </p>
        <p>However, note that it is possible to set a no_escape flag (but you probably don't want to do this):</p>
        <pre><code>- test = php('$foo', true);

will asign to variable test:

&lt;?php echo $foo; ?&gt;</code></pre>
        <p>## Usage</p>
        <pre><code>var jade = require('jade');
var jade4php = require('jade4php');

jade4php(jade);

var html = jade.render('string of jade');</code></pre>
        <p>## Example</p>
        <pre><code>doctype html
//- normal jade variable
- title = 'Example & Test';
//- php function call to format an escaped 
//- echo statement of expression argument
- test = php('$test_var + 1');
//- php function call to format an echo 
//- statement of expression argument without escape prcessing
- bad = php('$foo', true);
html
  head
    // normal jade interpolation
    title Jade4PHP example - Introduction
  body
    // php filter
    :php if ($test == 1):
    p PHP variable $test has value of 1
    :php else:
    p PHP variable $test has some other value
    :php endif;
    p
      :php(echo) 'SINGLE LINE <echo&gt; with escape'
    // normal jade interpolation
    p.
      This way is shortest if you need big &excl;{test}
      blocks of text spanning multiple
      lines.
    // note that these interpolations of PHP strings must not be escaped
    p!= test
    p!= bad
    // what happens when the PHP string is escaped
    p= test</code></pre>
        <p>Will produce:</p>
        <pre><samp>&lt;!DOCTYPE html&gt;
&lt;html&gt;
  &lt;head&gt;
    &lt;!-- normal jade interpolation--&gt;
    &lt;title&gt;Example &amp; Test&lt;/title&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;!-- php filter--&gt;
    &lt;?php if ($test == 1): ?&gt;
    &lt;p&gt;PHP variable $test has value of 1&lt;/p&gt;
    &lt;?php else: ?&gt;
    &lt;p&gt;PHP variable $test has some other value&lt;/p&gt;
    &lt;?php endif; ?&gt;
    &lt;p&gt;&lt;?php echo htmlspecialchars('SINGLE LINE &lt;echo&gt; with escape', ENT_QUOTES, 'UTF-8'); ?&gt;
    &lt;/p&gt;
    &lt;!-- normal jade interpolation--&gt;
    &lt;p&gt;
      This way is shortest if you need big &lt;?php echo htmlspecialchars($test_var + 1, ENT_QUOTES, 'UTF-8'); ?&gt;
      blocks of text spanning multiple
      lines.
    &lt;/p&gt;
    &lt;!-- note that these interpolations of PHP strings must not be escaped--&gt;
    &lt;p&gt;&lt;?php echo htmlspecialchars($test_var + 1, ENT_QUOTES, 'UTF-8'); ?&gt;&lt;/p&gt;
    &lt;p&gt;&lt;?php echo $foo; ?&gt;&lt;/p&gt;
    &lt;!-- what happens when the PHP string is escaped--&gt;
    &lt;p&gt;&lt;?php echo htmlspecialchars($test_var + 1, ENT_QUOTES, 'UTF-8'); ?&gt;&lt;/p&gt;
  &lt;/body&gt;
&lt;/html&gt;</samp></pre>
      </article>
    </section>
    <footer class="row txt-center">
      <nav class="navfoot">  
        <ul>    
          <li><a href="setup.php">Setup</a></li>
          <li><a href="project.php">Project Folders</a></li>
          <li><a href="paras.php">Paragraph Text</a></li>
          <li><a href="tables.php">Tables</a></li>
          <li><a href="menu.php">Menus</a></li>
          <li><a href="conditional.php">Conditional PHP</a></li>
          <li><a href="amazium.php">Amazium CSS</a></li>
          <li><a href="forms.php">Amazium Forms</a></li>
        </ul>
      </nav>Copyright 2014 <a href="http://www.jade4php.com">www.jade4php.com</a>. All rights reserved.<br>
    </footer>
    <script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="js/amazium.js"></script>
  </body>
</html>