<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Jade4PHP example - Paragraph Text</title>
    <meta name="description" content="">
    <meta name="author" content=""><!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,300,400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/base.css">
    <link rel="stylesheet" href="css/amazium.css">
    <link rel="stylesheet" href="css/form.css">
    <link rel="stylesheet" href="css/layout.css">
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon.png">
  </head>
  <body>
    <header class="row">
      <div class="grid_6"><a href="https://github.com/BookArt/jade4php" target="_blank">
          <image src="img/logo.png"></image></a></div>
      <div class="grid_6 txt-right">
        <h3> <a href="https://github.com/BookArt/jade4php-example/archive/master.zip">download&nbsp;<span class="fa fa-download"></span></a></h3><br>
        <div class="social">&nbsp
        </div>
      </div>
      <hr>
    </header>
    <section class="row"><br>
      <h2 class="page-title">Getting started with jade4php</h2><br>
    </section>
    <section class="row">
      <article class="grid_3">
        <nav class="navpanel">
          <ol>    
            <li><a href="index.php"><span class="number"></span><span class="label">introduction</span></a><span class="arrow"></span></li>
            <li><a href="setup.php"><span class="number"></span><span class="label">Setup</span></a><span class="arrow"></span></li>
            <li><a href="project.php"><span class="number"></span><span class="label">Project Folders</span></a><span class="arrow"></span></li>
            <li class="selected"><a href="#"><span class="number"></span><span class="label">Paragraph Text</span></a><span class="arrow"></span></li>
            <li><a href="tables.php"><span class="number"></span><span class="label">Tables</span></a><span class="arrow"></span></li>
            <li><a href="menu.php"><span class="number"></span><span class="label">Menus</span></a><span class="arrow"></span></li>
            <li><a href="conditional.php"><span class="number"></span><span class="label">Conditional PHP</span></a><span class="arrow"></span></li>
            <li><a href="amazium.php"><span class="number"></span><span class="label">Amazium CSS</span></a><span class="arrow"></span></li>
            <li><a href="forms.php"><span class="number"></span><span class="label">Amazium Forms</span></a><span class="arrow"></span></li>
          </ol>
        </nav>
      </article>
      <article class="grid_9">
        <h2>Paragraph Text</h2>
        <p><?php echo htmlspecialchars($para_1, ENT_QUOTES, 'UTF-8'); ?>
        </p>
        <p><?php echo htmlspecialchars($para_2, ENT_QUOTES, 'UTF-8'); ?>
        </p>
        <h3>paras.jade</h3>
        <pre><code>p
  :php(echo) $para_1
p
  :php(echo) $para_2         </code></pre>
        <h3>paras.php</h3>
        <pre><code>&lt;?php
include "lib/Template.class.php";
$template = new Template();

$p1 = &lt;&lt;&lt;'EOT1'
&lt;Lorem &amp; ipsum&gt; dolor sit amet, consectetur adipiscing elit. 
Donec pellentesque, ex a condimentum finibus, ex lorem egestas nisi, 
non semper lectus libero id ante. Maecenas eu faucibus magna. 
Aliquam eget sapien aliquet, venenatis tellus ut, tincidunt magna. 
Nunc ut nulla pharetra, commodo mauris sed, posuere tellus. Donec 
mattis magna id pharetra ornare. Sed ultricies commodo faucibus. 
Morbi fringilla aliquet ex non mollis. Etiam ut nulla ut nulla 
vestibulum consectetur a id mi. Integer tincidunt semper vestibulum. 
Pellentesque lobortis lacus eget est interdum, sed pharetra nisl 
malesuada. Pellentesque luctus nunc nec velit egestas pretium vel 
a lorem. Aenean sagittis nulla dolor, id malesuada sapien mattis eu. 
Class aptent taciti sociosqu ad litora torquent per conubia nostra, 
per inceptos himenaeos. Duis sollicitudin, lectus et tempor mattis, 
orci turpis tincidunt dolor, et malesuada lacus est ac orci.
EOT1;

$p2 = &lt;&lt;&lt;'EOT2'
Nullam a dolor id arcu semper finibus ut pulvinar orci. Proin 
sodales nisi et dictum pulvinar. Duis orci velit, suscipit et 
porttitor gravida, molestie ac purus. Cum sociis natoque penatibus 
et magnis dis parturient montes, nascetur ridiculus mus. Cras felis 
neque, gravida a blandit ac, rutrum ut sapien. Vivamus tincidunt 
volutpat libero eget tempor. Nam dolor mauris, mollis in euismod 
vitae, viverra ac libero
EOT2;

$template-&gt;assign('para_1', $p1);
$template-&gt;assign('para_2', $p2);
$template-&gt;display('templates/paras.phtml');</code></pre>
      </article>
    </section>
    <footer class="row txt-center">
      <nav class="navfoot">  
        <ul>    
          <li><a href="index.php">introduction</a></li>
          <li><a href="setup.php">Setup</a></li>
          <li><a href="project.php">Project Folders</a></li>
          <li><a href="tables.php">Tables</a></li>
          <li><a href="menu.php">Menus</a></li>
          <li><a href="conditional.php">Conditional PHP</a></li>
          <li><a href="amazium.php">Amazium CSS</a></li>
          <li><a href="forms.php">Amazium Forms</a></li>
        </ul>
      </nav>Copyright 2014 <a href="http://www.jade4php.com">www.jade4php.com</a>. All rights reserved.<br>
    </footer>
    <script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="js/amazium.js"></script>
  </body>
</html>