<!DOCTYPE html>
<html lang="en">
  <head>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]--> 
    <meta charset="utf-8">
    <title>Jade4PHP - Project Folders</title>
    <meta name="description" content="Jade4PHP is a an extension for Jade.js allowing you to create beautiful jade templates for PHP">
    <meta name="author" content="Brian Etherington">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,300,400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/base.css">
    <link rel="stylesheet" href="css/amazium.css">
    <link rel="stylesheet" href="css/form.css">
    <link rel="stylesheet" href="css/layout.css">
    <link rel="shortcut icon" href="img/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon.png">
  </head>
  <body>
    <header class="row">
      <div class="grid_6"><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-screen">
            <image src="img/logo.png"></image></a></span><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-tablet">
            <image src="img/logo.png"></image></a></span><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-mobile float-left">
            <image src="img/logo.png" width="200px"></image></a></span><span><a id="navigation-btn" href="#" class="show-mobile"> <span class="fa fa-bars fa-2x"></span></a></span></div>
      <div class="grid_6 txt-right">
        <h3 class="download"><a href="https://github.com/BookArt/jade4php-example/archive/master.zip">download&nbsp;<span class="fa fa-download"></span></a></h3>
        <div class="social">
          <!-- AddToAny BEGIN-->
          <div class="a2a_kit a2a_kit_size_32 a2a_default_style"><a class="a2a_button_facebook"></a><a class="a2a_button_twitter"></a><a class="a2a_button_google_plus"></a><a class="a2a_button_tumblr"></a>
          </div>
          <script type="text/javascript">
            var a2a_config = a2a_config || {};
            a2a_config.linkname = "jade4php";
            a2a_config.linkurl = "http://www.jade4php.com";
          </script>
          <script type="text/javascript" src="//static.addtoany.com/menu/page.js"></script>
          <!-- AddToAny END-->
        </div>
      </div>
      <hr>
    </header>
    <section class="row"><br>
      <h2 class="indent">Getting started with jade4php</h2><br>
    </section>
    <section class="row">
      <article id="navigation" class="grid_3">
        <nav class="navpanel">
          <ol>    
            <li><a href="index.php"><span class="number"></span><span class="label">Introduction</span></a><span class="arrow"></span></li>
            <li><a href="setup.php"><span class="number"></span><span class="label">Setup</span></a><span class="arrow"></span></li>
            <li class="selected"><a href="#"><span class="number"></span><span class="label">Project Folders</span></a><span class="arrow"></span></li>
            <li><a href="paras.php"><span class="number"></span><span class="label">Paragraph Text</span></a><span class="arrow"></span></li>
            <li><a href="tables.php"><span class="number"></span><span class="label">Tables</span></a><span class="arrow"></span></li>
            <li><a href="menu.php"><span class="number"></span><span class="label">Menus</span></a><span class="arrow"></span></li>
            <li><a href="conditional.php"><span class="number"></span><span class="label">Conditional PHP</span></a><span class="arrow"></span></li>
            <li><a href="amazium.php"><span class="number"></span><span class="label">Amazium CSS</span></a><span class="arrow"></span></li>
            <li><a href="forms.php"><span class="number"></span><span class="label">Amazium Forms</span></a><span class="arrow"></span></li>
          </ol>
        </nav>
      </article>
      <article class="grid_9">
        <h2>Project Folders</h2>
        <p>The example project is organised as follows:</p>
        <ol class="treelist">
          <li class="folder">Your project folder
            <ol class="treelist">
              <li class="folder">htdocs<br>
                <p>This is the web root folder for your project.</p>
                <ol class="treelist">
                  <li class="folder">css<br>
                    <p>This folder contains all of the stylesheets for the project.</p>
                  </li>
                  <li class="folder">img<br>
                    <p>This folder contains all of the images for the project.        </p>
                  </li>
                  <li class="folder">js<br>
                    <p>This folder contains all of the javascript file for the project.        </p>
                  </li>
                  <li class="folder">lib<br>
                    <p>This folder contains PHP classes used in the project.        </p>
                  </li>
                  <li class="folder">templates<br>
                    <p>This folder contains the generated  .phtml template files used in the project.       </p>
                  </li>
                  <li class="file">PHP Source Files</li>
                </ol>
              </li>
              <li class="folder">jade
                <ol class="treelist">
                  <li class="folder">layout<br>
                    <p>This folder contains the jade master layout templates.        </p>
                  </li>
                  <li class="folder">mixins<br>
                    <p>This folder contains the jade mixins used in the project (e.g. menus)        </p>
                  </li>
                  <li class="file">Jade Templates</li>
                </ol>
              </li>
              <li class="folder">node_modules<br>
                <p>This folder contains the node.js modules required by your project.   </p>
              </li>
              <li class="file">Gruntfile.js<br>
                <p>This is the grunt task file to perform the taks you will need in your development workflow (e.g. compile the jade templates)   </p>
              </li>
              <li class="file">package.json<br>
                <p>This file contains the definition of the node.js dependencies for the node package manager (npm)     </p>
              </li>
              <li class="file">phpinfo.php<br>
                <p>phpinfo file to check that php is installed correctly.</p>
              </li>
            </ol>
          </li>
        </ol>
      </article>
    </section>
    <footer class="row txt-center">
      <nav class="navfoot">  
        <ul>    
          <li><a href="index.php">Introduction</a></li>
          <li><a href="setup.php">Setup</a></li>
          <li><a href="paras.php">Paragraph Text</a></li>
          <li><a href="tables.php">Tables</a></li>
          <li><a href="menu.php">Menus</a></li>
          <li><a href="conditional.php">Conditional PHP</a></li>
          <li><a href="amazium.php">Amazium CSS</a></li>
          <li><a href="forms.php">Amazium Forms</a></li>
        </ul>
      </nav>Copyright 2014 <a href="http://www.jade4php.com">www.jade4php.com</a>. All rights reserved.<br>
    </footer>
    <script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="js/amazium.js"></script>
    <script type="text/javascript">
      function toggleNavigationClass() {
        if ( document.getElementById('navigation').className.match(/(?:^|\s)showme(?!\S)/) ) {
          document.getElementById('navigation').className =
              document.getElementById('navigation').className.replace( /(?:^|\s)showme(?!\S)/g , '' );
        } else {
          document.getElementById("navigation").className += " showme";
        }
      }
      window.onload = function() {
        var navigationBtnId = document.getElementById('navigation-btn');
        if (navigationBtnId != null) {
          navigationBtnId.addEventListener( 'click' , toggleNavigationClass );
        }
      }
    </script>
  </body>
</html>