<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Jade4PHP example - Project Folders</title>
    <meta name="description" content="">
    <meta name="author" content=""><!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,300,400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/base.css">
    <link rel="stylesheet" href="css/amazium.css">
    <link rel="stylesheet" href="css/form.css">
    <link rel="stylesheet" href="css/layout.css">
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon.png">
  </head>
  <body>
    <header class="row">
      <div class="grid_6"><a href="https://github.com/BookArt/jade4php" target="_blank">
          <image src="img/logo.png"></image></a></div>
      <div class="grid_6 txt-right">
        <h3> <a href="https://github.com/BookArt/jade4php-example/archive/master.zip">download&nbsp;<span class="fa fa-download"></span></a></h3><br>
        <div class="social">&nbsp
        </div>
      </div>
      <hr>
    </header>
    <section class="row"><br>
      <h2 class="page-title">Getting started with jade4php</h2><br>
    </section>
    <section class="row">
      <article class="grid_3">
        <nav class="navpanel">
          <ol>    
            <li><a href="index.php"><span class="number"></span><span class="label">introduction</span></a><span class="arrow"></span></li>
            <li><a href="setup.php"><span class="number"></span><span class="label">Setup</span></a><span class="arrow"></span></li>
            <li class="selected"><a href="#"><span class="number"></span><span class="label">Project Folders</span></a><span class="arrow"></span></li>
            <li><a href="paras.php"><span class="number"></span><span class="label">Paragraph Text</span></a><span class="arrow"></span></li>
            <li><a href="tables.php"><span class="number"></span><span class="label">Tables</span></a><span class="arrow"></span></li>
            <li><a href="menu.php"><span class="number"></span><span class="label">Menus</span></a><span class="arrow"></span></li>
            <li><a href="conditional.php"><span class="number"></span><span class="label">Conditional PHP</span></a><span class="arrow"></span></li>
            <li><a href="amazium.php"><span class="number"></span><span class="label">Amazium CSS</span></a><span class="arrow"></span></li>
            <li><a href="forms.php"><span class="number"></span><span class="label">Amazium Forms</span></a><span class="arrow"></span></li>
          </ol>
        </nav>
      </article>
      <article class="grid_9">
        <h2>Project Folders</h2>
        <p>The example project is organised as follows:</p>
        <ol class="treelist">
          <li class="folder">Your project folder
            <ol class="treelist">
              <li class="folder">htdocs<br><span>This is the web root folder for your project.</span>
                <ol class="treelist">
                  <li class="folder">css<br><span>This folder contains all of the stylesheets for the project.</span></li>
                  <li class="folder">img<br><span>This folder contains all of the images for the project.        </span></li>
                  <li class="folder">js<br><span>This folder contains all of the javascript file for the project.        </span></li>
                  <li class="folder">lib<br><span>This folder contains PHP classes used in the project.        </span></li>
                  <li class="folder">templates<br><span>This folder contains the generated  .phtml template files used in the project.       </span></li>
                  <li class="file">PHP Source Files</li>
                </ol>
              </li>
              <li class="folder">jade
                <ol class="treelist">
                  <li class="folder">layout<br><span>This folder contains the jade master layout templates.        </span></li>
                  <li class="folder">mixins<br><span>This folder contains the jade mixins used in the project (e.g. menus)        </span></li>
                  <li class="file">Jade Templates</li>
                </ol>
              </li>
              <li class="folder">node_modules<br><span>This folder contains the node.js modules required by your project.   </span></li>
              <li class="file">Gruntfile.js<br><span>This is the grunt task file to perform the taks you will need in your development workflow (e.g. compile the jade templates)   </span></li>
              <li class="file">package.json<br><span>This file contains the definition of the node.js dependencies for the node package manager (npm)     </span></li>
              <li class="file">phpinfo.php<br><span>phpinfo file to check that php is installed correctly.</span></li>
            </ol>
          </li>
        </ol>
      </article>
    </section>
    <footer class="row txt-center">
      <nav class="navfoot">  
        <ul>    
          <li><a href="index.php">introduction</a></li>
          <li><a href="setup.php">Setup</a></li>
          <li><a href="paras.php">Paragraph Text</a></li>
          <li><a href="tables.php">Tables</a></li>
          <li><a href="menu.php">Menus</a></li>
          <li><a href="conditional.php">Conditional PHP</a></li>
          <li><a href="amazium.php">Amazium CSS</a></li>
          <li><a href="forms.php">Amazium Forms</a></li>
        </ul>
      </nav>Copyright 2014 <a href="http://www.jade4php.com">www.jade4php.com</a>. All rights reserved.<br>
    </footer>
    <script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="js/amazium.js"></script>
  </body>
</html>