<!DOCTYPE html>
<html lang="en">
  <head>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]--> 
    <meta charset="utf-8">
    <title>Jade4PHP - Setup</title>
    <meta name="description" content="Jade4PHP is a an extension for Jade.js allowing you to create beautiful jade templates for PHP">
    <meta name="author" content="Brian Etherington">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,300,400" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/base.css">
    <link rel="stylesheet" href="css/amazium.css">
    <link rel="stylesheet" href="css/form.css">
    <link rel="stylesheet" href="css/layout.css">
    <link rel="shortcut icon" href="img/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon.png">
  </head>
  <body>
    <header class="row">
      <div class="grid_6"><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-screen">
            <image src="img/logo.png"></image></a></span><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-tablet">
            <image src="img/logo.png"></image></a></span><span><a href="https://github.com/BookArt/jade4php" target="_blank" class="show-mobile float-left">
            <image src="img/logo.png" width="200px"></image></a></span><span><a id="navigation-btn" href="#" class="show-mobile"> <span class="fa fa-bars fa-2x"></span></a></span></div>
      <div class="grid_6 txt-right">
        <h3 class="download"><a href="https://github.com/BookArt/jade4php-example/archive/master.zip">download&nbsp;<span class="fa fa-download"></span></a></h3>
        <div class="social">
          <!-- AddToAny BEGIN-->
          <div class="a2a_kit a2a_kit_size_32 a2a_default_style"><a class="a2a_button_facebook"></a><a class="a2a_button_twitter"></a><a class="a2a_button_google_plus"></a><a class="a2a_button_tumblr"></a>
          </div>
          <script type="text/javascript">
            var a2a_config = a2a_config || {};
            a2a_config.linkname = "jade4php";
            a2a_config.linkurl = "http://www.jade4php.com";
          </script>
          <script type="text/javascript" src="//static.addtoany.com/menu/page.js"></script>
          <!-- AddToAny END-->
        </div>
      </div>
      <hr>
    </header>
    <section class="row"><br>
      <h2 class="indent">Getting started with jade4php</h2><br>
    </section>
    <section class="row">
      <article id="navigation" class="grid_3">
        <nav class="navpanel">
          <ol>    
            <li><a href="index.php"><span class="number"></span><span class="label">Introduction</span></a><span class="arrow"></span></li>
            <li class="selected"><a href="#"><span class="number"></span><span class="label">Setup</span></a><span class="arrow"></span></li>
            <li><a href="project.php"><span class="number"></span><span class="label">Project Folders</span></a><span class="arrow"></span></li>
            <li><a href="paras.php"><span class="number"></span><span class="label">Paragraph Text</span></a><span class="arrow"></span></li>
            <li><a href="tables.php"><span class="number"></span><span class="label">Tables</span></a><span class="arrow"></span></li>
            <li><a href="menu.php"><span class="number"></span><span class="label">Menus</span></a><span class="arrow"></span></li>
            <li><a href="conditional.php"><span class="number"></span><span class="label">Conditional PHP</span></a><span class="arrow"></span></li>
            <li><a href="amazium.php"><span class="number"></span><span class="label">Amazium CSS</span></a><span class="arrow"></span></li>
            <li><a href="forms.php"><span class="number"></span><span class="label">Amazium Forms</span></a><span class="arrow"></span></li>
          </ol>
        </nav>
      </article>
      <article class="grid_9">
        <h2>Setup</h2>
        <p>To create, run, and debug your Jade4PHP projects you will need the following software:</p>
        <ol>
          <li>
            <p>Download the <a href="https://github.com/BookArt/jade4php-example/archive/master.zip">jade4php example website</a> and unzip it to your project folder.</p>
          </li>
          <li>
            <p>
               
              Download and install node.js from <a href="http://nodejs.org/download/" target="_blank">http://nodejs.org/download</a>
            </p>
          </li>
          <li>
            <p>
              Open a terminal window and navigate to the folder where you installed the example 
              website in step (1) and type 
            </p>
            <pre><code>npm install</code></pre>
            <p>
               
              This will install the node.js dependencies defined in package.json for your project so that 
              you can run jade using grunt.
            </p>
          </li>
          <li>
            <p>Install grunt-cli using the node package manager npm (already installed with node above)</p>
            <pre><code>npm install -g grunt-cli</code></pre>
            <p>For further information about grunt and what it can do see <a href="http://gruntjs.com/" target="_blank">http://gruntjs.com/</a></p>
          </li>
          <li>
            <p>In the terminal window type grunt </p>
            <pre>
              <p>&gt;grunt
Running "clean:compile" (clean) task
&gt;&gt; 8 paths cleaned.

Running "jade4php:compile" (jade4php) task
File htdocs/templates/amazium.phtml created.
File htdocs/templates/conditional.phtml created.
File htdocs/templates/forms.phtml created.
File htdocs/templates/intro.phtml created.
File htdocs/templates/menu.phtml created.
File htdocs/templates/paras.phtml created.
File htdocs/templates/setup.phtml created.
File htdocs/templates/tables.phtml created.

Done, without errors.
              </p></pre><br>
            <p>Templates in jade4php_example/jade will be compiled as .phtml files to jade4php_example/htdocs/templates.</p>
            <p>Have a look at the jade templates and the equivalent .phtml files to see what has been generated.</p>
          </li>
          <li>
            <p>If you do not already have one, you will need a Web Server with support for PHP. </p>
            <p>
              If you want to get up and running quickly, you can use the development web server built into PHP.  
              Download and install PHP from <a href="http://www.php.net/downloads.php" target="_blank">http://www.php.net/downloads.php</a>
            </p>
            <p>
               
              Full instructions for configuration and installation can be found at <a href="http://php.net/manual/en/install.php" target="_blank">http://php.net/manual/en/install.php</a>
            </p>
            <p>
               You will be using the Command Line PHP so make sure the path to the php executable is in your 
              PATH environment if you are using Microsoft Windows.
              <ul class="square">
                <li>
                  <p>
                     
                    Open a second terminal window, navigate to the jade4php projects folder and type...
                    <pre><code>cd htdocs
php -S localhost:8000</code></pre>This will start a web server on port 8000 with document root your project's htdocs folder.
                  </p>
                </li>
                <li>
                  <p>In a browser type
                    <pre><code>localhost:8000/phpinfo.php</code></pre>This should display information about the installed version of php.  
                    If you receive an error, go back and check your installation and configuration of PHP.
                  </p>
                </li>
                <li>
                  <p>In your browser type
                    <pre><code>localhost:8000/index.php</code></pre>This will display the home page of the example website..  
                  </p>
                </li>
              </ul>
            </p>
            <p>
              Alternatively, PHP support can be added to a number of web servers (IIS, Xitami, and so on), 
              but most commonly Apache HTTP Server is used. Go to  <a href="http://httpd.apache.org/docs/current/install.html" target="_blank">http://httpd.apache.org/docs/current/install.html </a>for information on how to install and configure Apache.
            </p>
          </li>
          <li>
            <p>
              edit jade4php_example/jade/intro.jade to change some text and save the edited file.  
              In the first terminal window type grunt to update the changed templates.
            </p>
            <pre>
              <p>&gt;grunt
Running "clean:compile" (clean) task
&gt;&gt; 8 paths cleaned.

Running "jade4php:compile" (jade4php) task
File htdocs/templates/amazium.phtml created.
File htdocs/templates/conditional.phtml created.
File htdocs/templates/forms.phtml created.
File htdocs/templates/intro.phtml created.
File htdocs/templates/menu.phtml created.
File htdocs/templates/paras.phtml created.
File htdocs/templates/setup.phtml created.
File htdocs/templates/tables.phtml created.

Done, without errors.
              </p></pre>
          </li>
          <li>
            <p>Refresh your browser to see the changes.              </p>
          </li>
        </ol>
      </article>
    </section>
    <footer class="row txt-center">
      <nav class="navfoot">  
        <ul>    
          <li><a href="index.php">Introduction</a></li>
          <li><a href="project.php">Project Folders</a></li>
          <li><a href="paras.php">Paragraph Text</a></li>
          <li><a href="tables.php">Tables</a></li>
          <li><a href="menu.php">Menus</a></li>
          <li><a href="conditional.php">Conditional PHP</a></li>
          <li><a href="amazium.php">Amazium CSS</a></li>
          <li><a href="forms.php">Amazium Forms</a></li>
        </ul>
      </nav>Copyright 2014 <a href="http://www.jade4php.com">www.jade4php.com</a>. All rights reserved.<br>
    </footer>
    <script type="text/javascript" src="js/jquery-1.8.0.min.js"></script>
    <script type="text/javascript" src="js/amazium.js"></script>
    <script type="text/javascript">
      function toggleNavigationClass() {
        if ( document.getElementById('navigation').className.match(/(?:^|\s)showme(?!\S)/) ) {
          document.getElementById('navigation').className =
              document.getElementById('navigation').className.replace( /(?:^|\s)showme(?!\S)/g , '' );
        } else {
          document.getElementById("navigation").className += " showme";
        }
      }
      window.onload = function() {
        var navigationBtnId = document.getElementById('navigation-btn');
        if (navigationBtnId != null) {
          navigationBtnId.addEventListener( 'click' , toggleNavigationClass );
        }
      }
    </script>
  </body>
</html>